config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :scenes, only: :index
  resources :importants, only: :index do
    collection do
      get :routing
      get :future
      get :get_typhoon
      get :get_by_unit
      get :get_rain
      get :get_warning
    end
  end
  resources :histories, only: :index do
    collection do
      get :list
      get :result
    end
  end
end

app/controllers/importants_controller.rb
class ImportantsController < ApplicationController
  def index
    warning_info = Weather.get_warning_data
    @warning_data = warning_info['data']
  end

  def get_by_unit
    warning_info = Weather.get_warning_data
    @warning_data = warning_info['data']
    #区县预警
    area_warning_info = Weather.get_area_warning_data(params[:unit])
    @area_warning_data = area_warning_info['data']
    respond_to do |format|
      format.js
    end
  end

  def get_warning
    @warning_data = params[:data]
  end

  #未来降水
  def future
    mappings = {"lon" => "lng", "lat" => "lat", "data" => "count"}
    rains = Weather.get_rain_data["data"].reject{|x| x['data'] == 0}
    arr = []
    rains.each do |obj|
      ps = ActiveSupport::JSON.decode(obj.to_json)
      arr.push Hash[ps.map {|k, v| [mappings[k], v] }]
    end
    @points = arr.reject{|x| x['count'] == 0}
    gon.points = @points.to_json

    #获取时间段内的数据
    unless params[:lng].present? && params[:lat].present?
      qpf_info = Weather.get_qpf_data(121.48, 31.22)
    else
      qpf_info = Weather.get_qpf_data(params[:lng], params[:lat])
    end
    @qpf_data = qpf_info["data"]["list"]
  end

  def get_rain
    qpf_info = Weather.get_qpf_data(params[:lng], params[:lat])
    @qpf_data = qpf_info['data']['list']
    p @qpf_data
    respond_to do |format|
      format.js
    end
  end

  #台风路径
  def routing
    #台风列表
    typhoons_info = Weather.get_typhoons_data
    #显示lastreporttime >= 当前时间减去一天的台风
    @typhoons_data = typhoons_info['data'].reject{|x| x['lastreporttime'] <= Time.now-2.month}

    #单个台风,获取单个台风[路径]数据列表的第一个，待确认
    @typhoon_recorder = Weather.get_typhoon_data(@typhoons_data[0]['typhoonid'])['data'][-1]

    @typhoon_recorders = Weather.get_typhoon_data(@typhoons_data[0]['typhoonid'])['data']
    gon.typhoon_recorder = @typhoon_recorder.to_json
    gon.typhoon_recorders = @typhoon_recorders.to_json
  end

  def get_typhoon
    #单个台风
    @typhoon_recorder = Weather.get_typhoon_data(params[:typhoonid])['data'][-1]

    #台风列表
    @typhoon_recorders = Weather.get_typhoon_data(params[:typhoonid])['data']
    gon.typhoon_recorder = @typhoon_recorder.to_json
    gon.typhoon_recorders = @typhoon_recorders.to_json
    #gon.typhoon_recorder = @typhoon_recorder.to_json
    respond_to do |format|
      format.js
    end
  end
end

app/views/importants/_data.html.erb
<% if typhoon_recorder.present? %>
  <tr>
    <th>中心风力</th>
    <td><%= typhoon_recorder["max_wind"]%>级</td>
  </tr>
  <tr>
    <th>七级风圈</th>
    <td><%= typhoon_recorder["seven_radius"] %>km</td>
  </tr>
  <tr>
    <th>十级风圈</th>
    <td><%= typhoon_recorder["ten_radius"] %>km</td>
  </tr>
  <tr class="dataArray" data-url=<%= typhoon_recorders.to_json %>></tr>
  <tr class="data" data-url=<%= typhoon_recorder.to_json %>></tr>
<% else %>
  <tr>
    <th>中心风力</th>
    <td>暂无数据</td>
  </tr>
  <tr>
    <th>七级风圈</th>
    <td>暂无数据</td>
  </tr>
  <tr>
    <th>十级风圈</th>
    <td>暂无数据</td>
  </tr>
<% end %>

<% content_for :scripts do %>
  <%= javascript_include_tag baidu_api(ENV['baidukey']), 'data-turbolinks-track' => false %>
  <%= javascript_include_tag "http://api.map.baidu.com/library/Heatmap/2.0/src/Heatmap_min.js", 'data-turbolinks-track' => false %>
  <%= javascript_include_tag "http://api.map.baidu.com/library/CurveLine/1.5/src/CurveLine.min.js", 'data-turbolinks-track' => false %>

  <script type="text/javascript">
    function loadTyphoon() {
      //初始化地图
      var recorders = $(".dataArray").data('url');
      var recorder = $(".data").data('url');

      var map = new BMap.Map("allmap");
      var mapPoint = new BMap.Point(116.2317, 39.5427);
      map.centerAndZoom(mapPoint, 5);  // 初始化地图,设置中心点坐标和地图级别
      map.enableScrollWheelZoom();  //开启鼠标滚轮缩放
      //台风路径画
      var image = "http://7xj8j2.com1.z0.glb.clouddn.com/iconfont-taifenglujing03.gif"
      var myIcon = new BMap.Icon(image, new BMap.Size(30,30));
      var point = new BMap.Point(recorder.lon, recorder.lat);
      var marker2 = new BMap.Marker(point,{icon:myIcon});  // 创建标注
      map.addOverlay(marker2);

      //台风级别颜色
      function selectColor(level) {
        if(level > 10.8 && level < 17.1){
          return "#2960af"
        }else if(level > 17.2 && level < 24.4){
          return "#fff900"
        }else if(level > 24.5 && level < 32.6){
          return "#ff8d00"
        }else if(level > 32.7 && level < 41.4){
          return "#ff2600"
        }else if(level > 41.5 && level < 50.9){
          return "#b037cd"
        }else if(level >= 51.0){
          return "#000000"
        }
      }

      var points = new Array();
      var levels = new Array();
      for(var i=0; i < recorders.length; i++) {
        var level = {
          max_wind: recorders[i].max_wind,
          position: {
            lng: recorders[i].lon,
            lat: recorders[i].lat
          }
        }
        levels.push(level)
        var pt = new BMap.Point(recorders[i].lon, recorders[i].lat);
        points.push(pt);
      }
      var curve = new BMapLib.CurveLine(points, {strokeColor:"#eb5405", strokeWeight:4, strokeOpacity:0}); //创建弧线对象
      map.addOverlay(curve); //添加到地图中

      //根据台风坐标创建圆形
      for(var i = 0; i < levels.length; i++) {
        var circle = new BMap.Circle(new BMap.Point(levels[i].position.lng, levels[i].position.lat), 25000, {strokeColor: selectColor(levels[i].max_wind), strokeWeight: 3, strokeOpacity: 1});
        circle.setFillColor(selectColor(levels[i].max_wind));
        circle.setFillOpacity(1);
        map.addOverlay(circle);
      }
    }
    $(function(){
      loadTyphoon();
      $('#typhoonid').change(function(){
        $.ajax({
          url: "/importants/get_typhoon",
          type: 'GET',
          data: {typhoonid: $(this).val()},
          success: function(){
            loadTyphoon();
          }
        })
      });
      //模态框响应
      function searchModal(){
        $(".modal-bg").show(300);
        $(".modal-content").show(300);
      }
      function shutModal() {
        $(".modal-bg").hide();
        $(".modal-content").hide();
      }

      //风险防范措施模态框
      $(".riskBtn").click(function(){
        searchModal();
      });
      $('.shutDown').click(function(e){
        shutModal();
      });

      //风险防范措施按钮宽度等于降水信息宽度
      var b_width = $(".typhoonInfo").width() + "px";
      $(".riskBtn").css("width", b_width);

      //台风示意图显示隐藏
      $(".warning-btn").click(function(e){
        $(".typhoon-list").slideToggle();
        if($(this).css("bottom") == "230px") {
          $(this).animate({"bottom": "60px"});
        } else {
          $(this).animate({"bottom": "230px"});
        }
      })

      //地图的高度等于屏幕的高度
      var c_Height=($(document).height() - 111) + "px";
      $(".mapbar").css("height",c_Height);
    });
  </script>
<% end %>

app/views/importants/_get_by_unit.html.erb
<div class="modal-title"><%= unit %>预警信息</div>
<div class="modal-body">
  <% if @area_warning_data.present? %>
    <% @area_warning_data[0..2].each do |data|%>
      <div class="modalContent">
        <div class="leftContent text-center">
          <%= image_tag(Weather.get_image_pic(data['type'], data['level'])) %>
        </div>
        <div class="rightContent">
          <h3><%= data['type'] %>&nbsp;<%= data['level'] %>预警</h3>
          <p><%= data['content'] %></p>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="alert text-center">该区域暂时无预警信息</p>
  <% end %>
</div>

app/views/importants/_rain_data.html.erb
<tr>
  <th>未来30min降水</th>
  <td id="date"><%= qpf_data[5]["d"]%>mm</td>
</tr>
<tr>
  <th>未来60min降水</th>
  <td id="weather"><%= qpf_data[10]["d"]%>mm</td>
</tr>
<tr>
  <th>未来90min降水</th>
  <td id="rain"><%= qpf_data[15]["d"]%>mm</td>
</tr>

app/views/importants/_typhoon_symbol.html.erb
<div class="warning-btn"><%= link_to image_tag("warning-btn.gif"), "javascript:void(0);"%></div>
<div class="typhoon-list">
  <ul>
    <li>
      <i class="circle black"></i>
      超强台风
    </li>
    <li>
      <i class="circle purple"></i>
      强台风
    </li>
    <li>
      <i class="circle red"></i>
      台风
    </li>
    <li>
      <i class="circle orange"></i>
      强热带风暴
    </li>
    <li>
      <i class="circle yellow"></i>
      热带风暴
    </li>
    <li>
      <i class="circle blue"></i>
      热带低压
    </li>
  </ul>
</div>

app/views/importants/_warning.html.erb
<div class="modal-title">上海市预警信息</div>
<div class="modal-body">
  <div class="modalContent">
    <div class="text-center">
      <%= image_tag(Weather.get_image_pic(warning_data['type'], warning_data['level'])) %>
    </div>
    <div class="text-center">
      <h3 class="title"><%= warning_data['type'] %>&nbsp;<%= warning_data['level'] %>预警</h3>
      <p class="content text-left"><%= warning_data['content'] %></p>
    </div>
  </div>
</div>

app/views/importants/future.html.erb
<% content_for :title do %>
  未来降水
<% end %>

<%= render "tabbar"%>

<div class="searchbar">
  <form action="">
    <div id="r-result"><input type="text" placeholder="请输入您要查询的地址" id="suggestId"></div>
    <!-- <input type="submit" value="搜索" class="submit"> -->
    <div id="searchResultPanel" style="border:1px solid #C0C0C0;width:150px;height:auto; display:none;"></div>
  </form>
</div>

<div class="mapbar">
  <div id="allmap"></div>
</div>

<%= link_to "javascript:void(0);", class: "leida" do %>
<% end %>

<div class="tipsContent">
  <div class="weather-info">
    <table>
      <tr>
        <th class="text-left">当前位置</th>
        <td id="address">上海市</td>
      </tr>
    </table>
    <table id="weather-info">
      <%= render partial: "rain_data", locals: {qpf_data: @qpf_data} %>
    </table>
  </div>
  <%= link_to "javascript:void(0);", class: "riskBtn" do %>
    <span>风险防范措施</span>
    <%= image_tag("svg/shou.svg")%>
  <% end -%>
</div>

<!-- 模态框 -->
<div class="modal-bg">
  <%= link_to image_tag("svg/cuo.svg"), "javascript:void(0);", class: "shutDown"%>
</div>
<div class="modal-content">
  <div class="modal-title">风险预防措施</div>
  <div class="modal-body">
    <div class="text-center">内容未定</div>
  </div>
</div>

<% content_for :scripts do %>
  <%= javascript_include_tag baidu_api(ENV['baidukey']), 'data-turbolinks-track' => false %>
  <%= javascript_include_tag "http://api.map.baidu.com/library/Heatmap/2.0/src/Heatmap_min.js", 'data-turbolinks-track' => false %>
  <%= javascript_include_tag "http://api.map.baidu.com/library/AreaRestriction/1.2/src/AreaRestriction_min.js", 'data-turbolinks-track' => false %>
  <script type="text/javascript">
    $(function(){
      //初始化地图
      var map = new BMap.Map("allmap", {minZoom:4,maxZoom:12});
      var point = new BMap.Point(121.48,31.22);
      map.centerAndZoom(point, 8);  // 初始化地图,设置中心点坐标和地图级别
      map.enableScrollWheelZoom();  //开启鼠标滚轮缩放

      //设置上海经纬度范围，左下角坐标和右上角坐标
      // var b = new BMap.Bounds(new BMap.Point(120.51, 30.40),new BMap.Point(122.12, 31.53));
      // try {
      //   BMapLib.AreaRestriction.setBounds(map, b);
      // } catch (e) {
      //   alert(e);
      // }

      var points = JSON.parse(gon.points);

      if(!isSupportCanvas()){
        alert('热力图目前只支持有canvas支持的浏览器,您所使用的浏览器不能使用热力图功能~')
      }
      heatmapOverlay = new BMapLib.HeatmapOverlay({
        "radius":20,
        'opacity': 0.7,
        'gradient': {0.01:'#94a5cb',0.05:'#94a5cb',0.1:'#94a5cb',0.41:'#94a5cb',0.5:'#94a5cb', 0.8:'#5d79b7', 1.0:'#4463aa'}
      });

      heatmapOverlay.disableMassClear = true;
      map.addOverlay(heatmapOverlay);
      heatmapOverlay.setDataSet({data:points, max:10});
      heatmapOverlay.hide();  //默认雷达云图隐藏

      //判断浏览区是否支持canvas
      function isSupportCanvas(){
        var elem = document.createElement('canvas');
        return !!(elem.getContext && elem.getContext('2d'));
      }

      //定位到当前位置
      var mk;
      var geolocation = new BMap.Geolocation();
      geolocation.getCurrentPosition(function(r){
        if(this.getStatus() == BMAP_STATUS_SUCCESS){
          var myIcon = new BMap.Icon("http://7xj8j2.com1.z0.glb.clouddn.com/myposition.png", new BMap.Size(30, 30));
          var mk = new BMap.Marker(r.point,{icon:myIcon});
          mk.disableMassClear();
          map.addOverlay(mk);
          map.panTo(r.point);
          $.ajax({
            type: "GET",
            url: "/importants/get_rain",
            data: {lng: r.point.lng, lat: r.point.lat}
          });
        }
        else {
          alert('failed'+this.getStatus());
        }
      },{enableHighAccuracy: true})
      //获取点击位置的解析区域
      var gc = new BMap.Geocoder();
      var maker;
      function showInfo(e){
        var pt = e.point;
        map.removeOverlay(maker)
        gc.getLocation(pt, function(rs){
          var addComp = rs.addressComponents;
          maker = new BMap.Marker(pt);
          map.addOverlay(maker);
          $("#address").text(addComp.district);
          $.ajax({
            type: "GET",
            url: "/importants/get_rain",
            data: {lng: e.point.lng, lat: e.point.lat}
          });
        });
      }
      map.addEventListener("click", showInfo);

      //搜索地址
      function G(id) {
        return document.getElementById(id);
      }
      var ac = new BMap.Autocomplete(    //建立一个自动完成的对象
        {"input" : "suggestId"
        ,"location" : map
      });

      ac.addEventListener("onhighlight", function(e) {  //鼠标放在下拉列表上的事件
      var str = "";
        var _value = e.fromitem.value;
        var value = "";
        if (e.fromitem.index > -1) {
          value = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
        }
        str = "FromItem<br />index = " + e.fromitem.index + "<br />value = " + value;
        value = "";
        if (e.toitem.index > -1) {
          _value = e.toitem.value;
          value = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
        }
        str += "<br />ToItem<br />index = " + e.toitem.index + "<br />value = " + value;
        G("searchResultPanel").innerHTML = str;
      });

      var myValue;
      ac.addEventListener("onconfirm", function(e) {    //鼠标点击下拉列表后的事件
      var _value = e.item.value;
        myValue = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
        G("searchResultPanel").innerHTML ="onconfirm<br />index = " + e.item.index + "<br />myValue = " + myValue;
        setPlace();
      });

      function setPlace(){
        map.clearOverlays();    //清除地图上所有覆盖物
        function myFun(){
          var pp = local.getResults().getPoi(0).point;    //获取第一个智能搜索的结果
          map.centerAndZoom(pp, 12);
          map.addOverlay(new BMap.Marker(pp));    //添加标注
          var inputVal = $("#suggestId").val();  //获取用户输入的值
          $("#address").text(inputVal);
        }
        var local = new BMap.LocalSearch(map, { //智能搜索
          onSearchComplete: myFun,
          renderOptions: {map: map}
        });
        local.search(myValue);
      }

      //雷达按钮效果
      $(".leida").click(function(){
        $(this).toggleClass("active");
        if($(this).attr('class') == "leida"){
          heatmapOverlay.hide();
        }else{
          heatmapOverlay.show();
        }
      })

      //地图的高度等于屏幕的高度
      var c_Height=($(document).height() - 171) + "px";
      $(".mapbar").css("height",c_Height).css("overflow", "hidden");

      //风险防范措施按钮宽度等于降水信息宽度
      var b_width = $(".weather-info").width() + "px";
      $(".riskBtn").css("width", b_width);

      //模态框响应
      function searchModal(){
        $(".modal-bg").show(300);
        $(".modal-content").show(300);
      }
      function shutModal() {
        $(".modal-bg").hide();
        $(".modal-content").hide();
      }
      //风险防范措施模态框
      $(".riskBtn").click(function(e){
        searchModal();
      });
      //点击x号关闭模态框
      $('.shutDown').click(function(){
        shutModal();
      });
    });
  </script>
<% end %>

<style type="text/css">
  .mapbar {
    height: 500px;
    width: 100%;
  }
  #allmap {
    width: 100%;
    height: 100%;
  }
</style>

app/views/importants/get_by_unit.js.erb
$(".modal-bg").slideDown('fast');
$(".modal-content").slideDown('slow');
$(".modal-content").html($("<%= escape_javascript(render partial: 'get_by_unit', locals: {unit: params[:unit]}) %>"));

app/views/importants/get_rain.js.erb
$("#weather-info").html($("<%= escape_javascript(render partial: 'rain_data', locals: {qpf_data: @qpf_data}) %>"));

app/views/importants/get_typhoon.js.erb
$("#data").empty();
$("#data").html("<%= j(render partial: 'data', locals: {typhoon_recorder: @typhoon_recorder, typhoon_recorders: @typhoon_recorders})%>")

app/views/importants/get_warning.js.erb
$(".modal-bg").slideDown('fast');
$(".modal-content").slideDown('slow');
$(".modal-content").html($("<%= escape_javascript(render partial: 'warning', locals: {warning_data: @warning_data}) %>"));

app/views/importants/index.html.erb
<% content_for :title do %>
  重要天气
<% end %>

<%= content_for :tabbar do %>
  <div class="tabContent">
    <%= link_to importants_path, class: "active br" do %>
      预警信号
    <% end %>
    <%= link_to future_importants_path, class: "br" do %>
      未来降雨
    <% end %>
    <%= link_to routing_importants_path do %>
      台风路径
    <% end %>
  </div>
<% end %>

<div class="mainContent">
  <div class="topBar">
    <% if @warning_data.present? %>
      <% @warning_data[0..2].each do |data|%>
        <section>
          <%= link_to image_tag(Weather.get_image_pic(data['type'], data['level'])), get_warning_importants_path(data: data), remote: true %>
        </section>
      <% end %>
    <% else %>
      <p class="alert text-center">全市暂时无预警信息</p>
    <% end %>
  </div>

  <div class="mainMap">
    <% jiading_warnings = Weather.get_area_warning_data("嘉定")['data'] %>
    <% if jiading_warnings.present? %>
      <div class="areaWarning jiading">
        <% jiading_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <% baoshan_warnings = Weather.get_area_warning_data("宝山")['data'] %>
    <% if baoshan_warnings.present? %>
      <div class="areaWarning baoshan">
        <% baoshan_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <% chongming_warnings = Weather.get_area_warning_data("崇明")['data'] %>
    <% if chongming_warnings.present? %>
      <div class="areaWarning chongming">
        <% chongming_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <% shanghai_warnings = Weather.get_warning_data['data'] %>
    <% if shanghai_warnings.present? %>
      <div class="areaWarning shanghai">
        <% shanghai_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <% pudong_warnings = Weather.get_area_warning_data("浦东")['data'] %>
    <% if pudong_warnings.present? %>
      <div class="areaWarning pudong">
        <% pudong_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <% minhang_warnings = Weather.get_area_warning_data("闵行")['data'] %>
    <% if minhang_warnings.present? %>
      <div class="areaWarning minhang">
        <% minhang_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <% fengxian_warnings = Weather.get_area_warning_data("奉贤")['data'] %>
    <% if fengxian_warnings.present? %>
      <div class="areaWarning fengxian">
        <% fengxian_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <% songjiang_warnings = Weather.get_area_warning_data("松江")['data'] %>
    <% if songjiang_warnings.present? %>
      <div class="areaWarning songjiang">
        <% songjiang_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>
    <% jinshan_warnings = Weather.get_area_warning_data("金山")['data'] %>
    <% if jinshan_warnings.present? %>
      <div class="areaWarning jinshan">
        <% jinshan_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>
    <% qingpu_warnings = Weather.get_area_warning_data("青浦")['data'] %>
    <% if qingpu_warnings.present? %>
      <div class="areaWarning pudong">
        <% qingpu_warnings[0..1].each do |data|%>
          <%= image_tag(Weather.get_image_pic(data['type'], data['level']), class: "image") %>
        <% end %>
       </div>
    <% end %>

    <%= image_tag("shanghai-bg.gif", usemap: "#areamap", style: "width: 980;") %>
    <map name="areamap" id="areamap" data-url=<%= get_by_unit_importants_path %>>
      <!-- 嘉定区 -->
      <area shape="rect" coords="260,90,400,300"  nohref="nohref" alt="嘉定" />
      <!-- 崇明岛 -->
      <area shape="rect" coords="557,74,843,190"  nohref="nohref" alt="崇明" />
      <!-- 宝山区 -->
      <area shape="rect" coords="428,110,548,260"  nohref="nohref" alt="宝山" />
      <!-- 市区 -->
      <area shape="rect" coords="500,280,837,400"  nohref="nohref" alt="上海" />
      <!-- 浦东新区 -->
      <area shape="rect" coords="638,380,963,523"  nohref="nohref" alt="浦东" />
      <!-- 奉贤区 -->
      <area shape="rect" coords="460,530,774,645"  nohref="nohref" alt="奉贤" />
      <!-- 闵行区 -->
      <area shape="rect" coords="430,412,606,510"  nohref="nohref" alt="闵行" />
      <!-- 松江区 -->
      <area shape="rect" coords="235,426,420,570"  nohref="nohref" alt="松江" />
      <!-- 金山区 -->
      <area shape="rect" coords="160,600,470,760"  nohref="nohref" alt="金山" />
      <!-- 青浦区 -->
      <area shape="rect" coords="20,280,220,520"  nohref="nohref" alt="青浦" />
    </map>
  </div>
</div>

<!-- 区县预警模态框 -->
<div class="modal-bg">
  <%= link_to image_tag("svg/cuo.svg"), "javascript:void(0);", class: "shutDown"  %>
</div>
<div class="modal-content">
  <%= render partial: "get_by_unit", locals: {unit: "上海"} %>
</div>

<% content_for :scripts do %>
  <%= javascript_include_tag "jquery.rwdImageMaps.min" %>
  <script type="text/javascript">
    $(document).ready(function(e) {
      $('img[usemap]').rwdImageMaps();
      var url = $("map").data('url');
      $('area').on('click', function(e) {
        $.ajax({
          type: "GET",
          url: url,
          data: {unit: $(this).attr("alt")}
        })
      });
      //模态框响应
      function searchModal(){
        $(".modal-bg").show(300);
        $(".modal-content").show(300);
      }
      function shutModal() {
        $(".modal-bg").hide();
        $(".modal-content").hide();
      }
      //点击x号关闭模态框
      $('.shutDown').click(function(){
        shutModal();
      });
    });
  </script>
<% end %>

app/views/importants/routing.html.erb
<% content_for :title do %>
  台风路径
<% end %>

<%= render "tabbar"%>

<div class="mapbar">
  <div id="allmap"></div>
</div>

<div class="typhoonInfo">
  <div class="typhoon-info">
    <table>
      <tr>
        <th>台风名称</th>
        <td>
          <div class="select">
            <%= select_tag "typhoonid", options_for_select(@typhoons_data.collect{|v| [v['cnname'].present? ? v['cnname'] : v['enname'] , v['typhoonid']]})%>
          </div>
        </td>
      </tr>
    </table>
    <table id="data" style="color: #fff!important;">
      <%= render partial: "data", locals: {typhoon_recorder: @typhoon_recorder, typhoon_recorders: @typhoon_recorders}%>
    </table>
  </div>
  <%= link_to "javascript:void(0);", class: "riskBtn" do %>
    <span>风险防范措施</span>
    <%= image_tag("svg/shou.svg")%>
  <% end %>
</div>

<!-- 模态框 -->
<div class="modal-bg">
  <%= link_to image_tag("svg/cuo.svg"), "javascript:void(0);", class: "shutDown"  %>
</div>
<div class="modal-content">
  <div class="modal-title">风险预防措施</div>
  <div class="modal-body">
    <div class="text-center">内容未定</div>
  </div>
</div>

<!-- 台风预警标示 -->
<%= render "typhoon_symbol"%>

<style type="text/css">
  .mapbar {
    margin-top: 55px;
    width: 100%;
  }
  #allmap {
    width: 100%;
    height: 100%;
  }
</style>