config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :scenes, only: :index
  resources :importants, only: :index do
    collection do
      get :routing
      get :future
      get :get_typhoon
      get :get_by_unit
      get :get_rain
      get :get_warning
    end
  end
  resources :histories, only: :index do
    collection do
      get :list
      get :result
    end
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def index
  end

  def list
  end

  def result
  end
end

app/views/histories/index.html.erb
<% content_for :title do %>
  历史查询
<% end %>

<div class="searchbar">
  <form action="">
    <div id="r-result"><input type="text" placeholder="请输入您要查询的地址" id="suggestId"></div>
    <!-- <input type="submit" value="搜索" class="submit"> -->
    <div id="searchResultPanel" style="border:1px solid #C0C0C0;width:150px;height:auto; display:none;"></div>
  </form>
</div>

<div class="mapbar">
  <div id="allmap"></div>
</div>

<!-- 模态框 -->
<div class="modal-bg">
  <%= link_to image_tag("svg/cuo.svg"), "javascript:void(0);", class: "shutDown"  %>
</div>
<div class="modal-content">
  <div class="searchBar">
    <div class="title">历史查询</div>
    <%= form_tag result_histories_path, method: :get do %>
      <div class="styled-input">
        <label for="">开始时间</label>
        <input type="date" id="beginDate">
      </div>
      <div class="styled-input">
        <label for="">结束时间</label>
        <input type="date" id="endDate">
      </div>
      <div class="styled-input">
        <label for="">灾害类型</label>
        <select name="" id="">
          <option value=""></option>
        </select>
      </div>
      <div class="btns">
        <input type="submit" value="我要查询" class="submit fleft active">
        <input type="submit" value="取消查询" class="cancel fright">
      </div>
    <% end %>
  </div>
</div>

<% content_for :scripts do %>
  <%= javascript_include_tag baidu_api(ENV['baidukey']) %>
  <script type="text/javascript">
    //初始化地图
    var map = new BMap.Map("allmap");
    var point = new BMap.Point(121.487899,31.249162);
    map.centerAndZoom(point, 15);  // 初始化地图,设置中心点坐标和地图级别
    map.enableScrollWheelZoom();  //开启鼠标滚轮缩放

    //定位到当前位置
    var geolocation = new BMap.Geolocation();
    var gc = new BMap.Geocoder();

    geolocation.getCurrentPosition(function(r){
      if(this.getStatus() == BMAP_STATUS_SUCCESS){
        gc.getLocation(r.point, function(rs){
          var addComp = rs.addressComponents;
          var sContent = "<div style='color: #eb5405; font-size: 16px;font-weight: bold;'>您定位的位置是：<br></div>";
          var buttons = "<div style='padding:1rem 0;'>是否确定定位<a href='javascript:void(0);' onclick='searchModal()' id='makeSure' style='background: #6da042; padding: .4rem 1rem; color: #fff;border-radius: .3rem;margin-left:1rem;'>确定</a><a href='javascript:void(0);' onclick='hideinfowindow()' class='callOff' style='background: #fff; padding: .4rem 1rem; color: #eb5405; border:solid 1px #eb5405; margin-left:1rem;border-radius: .3rem;'>取消</a></div>"
          var position = addComp.district + addComp.street + addComp.streetNumber;
          var infoWindow = new BMap.InfoWindow(sContent + position + buttons);
          map.openInfoWindow(infoWindow,new BMap.Point(r.point.lng, r.point.lat));
        });
      }
      else {
        alert('failed'+this.getStatus());
      }
    },{enableHighAccuracy: true})

    function hideinfowindow(){
      map.clearOverlays();
    }

    //获取点击位置的解析区域
    function showInfo(e){
      var pt = e.point;
      map.clearOverlays();  //删除旧遮盖物
      gc.getLocation(pt, function(rs){
        var addComp = rs.addressComponents;
        map.addOverlay(new BMap.Marker(pt))  //添加新的遮盖物
        var sContent = "<div style='color: #eb5405; font-weight: bold;'>您现在的位置是：<br></div>";
        var buttons = "<div style='padding:1rem 0;'>是否确定定位<a href='javascript:void(0);' onclick='searchModal()' id='makeSure' style='background: #6da042; padding: .4rem 1rem; color: #fff;border-radius: .3rem;margin-left:1rem;'>确定</a><a href='javascript:void(0);' onclick='hideinfowindow()' class='callOff' style='background: #fff; padding: .4rem 1rem; color: #eb5405; border:solid 1px #eb5405; margin-left:1rem;border-radius: .3rem;'>取消</a></div>"
        var position = addComp.district + addComp.street + addComp.streetNumber;
        var opts = {
          width : 100,     // 信息窗口宽度
          height: 80,     // 信息窗口高度
          title : sContent  // 信息窗口标题
        }
        var infoWindow = new BMap.InfoWindow(position + buttons, opts);
        map.openInfoWindow(infoWindow,new BMap.Point(e.point.lng, e.point.lat));
      });
    }
    map.addEventListener("click", showInfo);

    //搜索地址
    function G(id) {
      return document.getElementById(id);
    }
    var ac = new BMap.Autocomplete(    //建立一个自动完成的对象
      {"input" : "suggestId"
      ,"location" : map
    });

    ac.addEventListener("onhighlight", function(e) {  //鼠标放在下拉列表上的事件
    var str = "";
      var _value = e.fromitem.value;
      var value = "";
      if (e.fromitem.index > -1) {
        value = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
      }
      str = "FromItem<br />index = " + e.fromitem.index + "<br />value = " + value;
      value = "";
      if (e.toitem.index > -1) {
        _value = e.toitem.value;
        value = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
      }
      str += "<br />ToItem<br />index = " + e.toitem.index + "<br />value = " + value;
      G("searchResultPanel").innerHTML = str;
    });

    var myValue;
    ac.addEventListener("onconfirm", function(e) {    //鼠标点击下拉列表后的事件
    var _value = e.item.value;
      myValue = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
      G("searchResultPanel").innerHTML ="onconfirm<br />index = " + e.item.index + "<br />myValue = " + myValue;
      setPlace();
    });

    function setPlace(){
      map.clearOverlays();    //清除地图上所有覆盖物
      function myFun(){
        var pp = local.getResults().getPoi(0).point;    //获取第一个智能搜索的结果
        map.centerAndZoom(pp, 12);
        gc.getLocation(pp, function(rs){
          var addComp = rs.addressComponents;
          map.addOverlay(new BMap.Marker(pp))  //添加新的遮盖物
          var sContent = "<div style='color: #eb5405; font-weight: bold;'>您现在的位置是：<br></div>";
          var buttons = "<div>是否确定定位<a href='javascript:void(0);' onclick='searchModal()' id='makeSure' style='background: #6da042; padding: .2rem 1rem; color: #fff;border-radius: .3rem;margin-left:1rem;'>确定</a><a href='javascript:void(0);' onclick='hideinfowindow()' class='callOff' style='background: #fff; padding: .2rem 1rem; color: #eb5405; border:solid 1px #eb5405; margin-left:1rem;border-radius: .3rem;'>取消</a></div>"
          var position = addComp.district + addComp.street + addComp.streetNumber;
          var infoWindow = new BMap.InfoWindow(sContent + position + buttons);
          map.openInfoWindow(infoWindow,new BMap.Point(pp.lng, pp.lat));
        });
      }
      var local = new BMap.LocalSearch(map, { //智能搜索
        onSearchComplete: myFun
      });
      local.search(myValue);
    }
    //模态框响应
    function searchModal(){
      $(".modal-bg").show(300);
      $(".modal-content").show(300);
    }
    function shutModal() {
      $(".modal-bg").hide();
      $(".modal-content").hide();
    }
    //点击x号关闭模态框
    $('.shutDown').click(function(){
      shutModal()
    });
    //点击取消查询关闭模态框
    $("input.cancel").click(function(){
      shutModal()
      return false;
    })

    //时间输入框默认填充当前日期
    Date.prototype.toDateInputValue = (function() {
      var local = new Date(this);
      local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
      return local.toJSON().slice(0,10);
    });
    $('#beginDate').val(new Date().toDateInputValue());
    $('#endDate').val(new Date().toDateInputValue());

    //地图的高度等于屏幕的高度
    var c_Height=($(document).height() - 116) + "px";
    $(".mapbar").css("height",c_Height);
  </script>
<% end %>

<style type="text/css">
  .mapbar {
    height: 500px;
    width: 100%;
  }
  #allmap {
    width: 100%;
    height: 100%;
  }
</style>

app/views/histories/list.html.erb
<div class="title">有N条记录达到赔偿标准，点击下面列表查看</div>
<div class="listBar">
  <% 5.times do %>
    <%= link_to "" do %>
      <div class="list">
        <div class="leftBar">
          <p>2015.6.6 17:00 ~ 2015.6.7 23:00</p>
          <p>累计雨量达200毫米</p>
        </div>
        <div class="rightArrow">
          <%= image_tag("svg/right-arrow.svg")%>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/histories/result.html.erb
<div class="logo">
  <%= image_tag("logo.png")%>
</div>

<ul class="result">
  <li>
    <%= image_tag("svg/dizhi.svg")%>
    <span>上海虹桥机场</span>
  </li>
  <li>
    <%= image_tag("svg/xingxing.svg")%>
    <span>气象理赔证明</span>
  </li>
  <li>
    <%= image_tag("svg/shizhong.svg")%>
    <span>2015-6-6 17:00 ~ 2015-6-7 23:00</span>
  </li>
  <li>
    <%= image_tag("svg/yu.svg")%>
    <span>每小时最大降雨233mm</span>
  </li>
  <li>
    <%= image_tag("svg/yu.svg")%>
    <span>每12小时最大降雨233mm</span>
  </li>
  <li>
    <%= image_tag("svg/yu.svg")%>
    <span>每24小时最大降雨233mm</span>
  </li>
</ul>
<hr>

<div class="tips">
  <p><span>暴雨标准：</span><br>指每小时降雨量达16毫米以上，或连续12小时降雨量达30毫米以上，或连续24小时降雨量达50毫米以上的降雨。</p>
</div>