config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :scenes, only: :index
  resources :importants, only: :index do
    collection do
      get :routing
      get :future
      get :get_typhoon
      get :get_by_unit
      get :get_rain
      get :get_warning
    end
  end
  resources :histories, only: :index do
    collection do
      get :list
      get :result
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper

  def baidu_api(key)
    "http://api.map.baidu.com/api?v=2.0&ak=" + key.to_s
  end

  # 根据日期获取周几
  def get_weekday datatime
    date = datatime.to_datetime
    if date.sunday?
      "星期日"
    elsif date.monday?
      "星期一"
    elsif date.tuesday?
      "星期二"
    elsif date.wednesday?
      "星期三"
    elsif date.thursday?
      "星期四"
    elsif date.friday?
      "星期五"
    elsif date.saturday?
      "星期六"
    end
  end

  #空气状况分类
  def aqi_level
    {
      "优" => "excellent",
      "良" => "good",
      "轻度污染" => "mild",
      "中度污染" => "moderate",
      "重度污染" => "severe",
      "严重污染" => "serious"
    }
  end

  #区县名称对应类
  def area_hash
    {
      '嘉定' => "jiading"
    }
  end
end

app/views/application/_footer.html.erb
<footer>
  <%= link_to root_path, class: "#{current_page?(controller: 'home', action: 'index') ? 'active' : ''}" do %>
    <div class="icon home"></div>
    <p>天气预报</p>
  <% end %>
  <%= link_to importants_path, class: "#{params[:controller] == 'importants' ? 'active' : ''}" do %>
    <div class="icon important"></div>
    <p>重要天气</p>
  <% end %>
  <%= link_to scenes_path, class: "#{params[:controller] == 'scenes' ? 'active' : ''}" do %>
    <div class="icon search"></div>
    <p>实况查询</p>
  <% end %>
  <%= link_to histories_path, class: "#{params[:controller] == 'histories' ? 'active' : ''}" do %>
    <div class="icon time"></div>
    <p>历史查询</p>
  <% end %>
</footer>

app/views/application/_tabbar.html.erb
<%= content_for :tabbar do %>
  <div class="tabContent">
    <%= link_to importants_path, class: "#{current_page?(controller: 'importants', action: 'index') ? 'active' : ''} br" do %>
      预警信号
    <% end %>
    <%= link_to future_importants_path, class: "#{current_page?(controller: 'importants', action: 'future') ? 'active' : ''} br" do %>
      未来降雨
    <% end %>
    <%= link_to routing_importants_path, class: "#{current_page?(controller: 'importants', action: 'routing') ? 'active' : ''}" do %>
      台风路径
    <% end %>
  </div>
<% end %>